<a href="https://colab.research.google.com/github/LSantana32/estructuraDeDatos-UNAHUR/blob/main/Copia_de_Trabajo_practico_4_Arreglos_com1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png) **Trabajo Práctico 4: Arreglos uni y multidimensionales** ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png)

En este trabajo práctico, vamos a trabajar con arreglos uni y multidimensionales en Python. Recuerden crear una copia de este archivo en su ***Google Drive*** para tener permisos de edición.

### Sergio: **sergio.gonzalez@unahur.edu.ar**



## **Vectores**

In [ ]:
import numpy as np

v1 = np.zeros(10, int)
v2 = np.array([2,3,1,4,6])
print(v1)
v1[0] = 20
v1[len(v1)-1] = 50
print(v2[3])

[0 0 0 0 0 0 0 0 0 0]
4


In [ ]:
#iterar el vector sobre los elementos
v2 = np.array([2,3,1,4,6])
print(v2)
#for var in v2: #reversed(v2) para recorrer de atras hacia adelante
#  print(var)

for pos in range(len(v2)): #0,1,2,3,4 / reversed(range(len(v2))) -> 4,3,2,1,0
  print(pos)
  v2[pos] = v2[pos]*2
print(v2)

In [ ]:
#notacion para acceder a regiones o subvectores
print(v2)
#v2[inicio:fin]
v3 = v2[1:4]
v3[0] = 20
print(v3)
print(v2)

[ 4  6  2  8 12]
[20  2  8]
[ 4 20  2  8 12]


In [ ]:
palabra = "casa"
#palabra[0] = 'p'
print(palabra[0])

c


In [ ]:
#indices negativos
#posicion del ultimo elemento: len(vector)-1 -> -1
print(v2)
print(v2[-1])

[ 4 20  2  8 12]
8


### **Ejercicio 1**

Escribir una función que recibe un numero entero N y le pide al usuario que ingrese N numeros. Al final, el programa debe retornar un vector contiendo los números que fueron ingresados. Tambien debe imprimir por pantalla la suma total de los valores y el promedio. Se deben hacer funciones para resolver el promedio y la suma total.

In [ ]:
import numpy as np

def sumaTotal(vector:np.array)->int:            #segunda parte
  suma=0
  for valor in vector:
    suma += valor
  return suma

def promedio(vector:np.array)->float:           #tercera parte
  return sumaTotal(vector)/len(vector)


def ingresarEntero(n:int,)->np.array:        #primera parte
  salida= np.zeros(n,int)
  for pos in range(len(salida)):    #len(salida) es el valor de iteraciones de salida y pos toma el valor 0,1,2,3,4...,n-1 (ya que empieza con 0 y no con 1), pos significa posicion, ya que analizas eso, no el valor
    salida[pos]= int(input("Ingrese un numero: "))
  print(sumaTotal(salida))
  print(promedio(salida))
  return salida




In [ ]:
v= ingresarEntero(5)
print(v)

Ingrese un numero: 4
Ingrese un numero: 5
Ingrese un numero: 6
Ingrese un numero: 7
Ingrese un numero: 8
30
6.0
[4 5 6 7 8]


### **Ejercicio 2**

Escribir una función que recibe un vector de strings y retorna otro con los mismos elementos del vector de entrada pero en orden inverso.

In [ ]:
def invertirArreglo(vector:np.array)->np.array:
  vectorInvertido= np.zeros(len(vector),str)
  pos=0
  for valor in reversed(vector):
    vectorInvertido[pos]=valor
    pos+=1
  return vectorInvertido



In [ ]:
palabra= np.array(["h","o","l","a"])
print (palabra)
print (invertirArreglo(palabra))

['h' 'o' 'l' 'a']
['a' 'l' 'o' 'h']


### **Ejercicio 3**

Escribir la función sumaDeVectores que recibe dos vectores de enteros del mismo tamaño y retorna otro con la suma de ambos. La suma de vectores se realiza componente a componente, segun la siguiente forma:

v<sub>1</sub> = [ v<sub>11</sub> , v<sub>12</sub> , v<sub>13</sub> , ... , v<sub>1N</sub> ]

v<sub>2</sub> = [ v<sub>21</sub> , v<sub>22</sub> , v<sub>23</sub> , ... , v<sub>2N</sub> ]

v<sub>1</sub> + v<sub>2</sub> = [ v<sub>11</sub> + v<sub>21</sub> , v<sub>12</sub> + v<sub>22</sub> , v<sub>13</sub> + v<sub>23</sub> , ... , v<sub>1N</sub> + v<sub>2N</sub> ]

In [ ]:
def sumaDeVectores(vector1:np.array,vector2:np.array)->np.array:
  salida= np.zeros(len(v1),int)
   for pos in range(len(salida)):
    salida[pos]= v1[pos]+v2[pos]
   return salida


In [ ]:
lista1 = [1, 2, 3, 4, 5, 6]
lista2 = [5, 6, 7, 8]

lista3 = lista1+lista2
print(lista3)


[1, 2, 3, 4, 5, 6, 5, 6, 7, 8]


### **Ejercicio 4**

Escribir una función que recibe un vector y desplaza todos sus elementos una posición hacia la derecha: el primero pasa a ser el segundo, el segundo pasa a ser el tercero y así sucesivamente. El último pasa a ser el primero.

Por ejemplo:

v1 = [2, 4, 1, 5, 7, **9**]

**desplazarADerecha(v1)**

=> v1 = [**9**, 2, 4, 1, 5, 7]

In [ ]:
import numpy as np

def desplazarADerecha(vector:np.array)->None:
  ultimo= vector[-1]
  for pos in reversed(range(0, len(vector)-1)):
    vector[pos+1]=vector[pos]
  v[0] = ultimo

In [ ]:
v=np.array([2,4,1,5,7,9])
print(v)
desplazarADerecha(v)
print(v)

[2 4 1 5 7 9]
[9 2 4 1 5 7]


### **Ejercicio 5**

Desarrollar una función que inserte un elemento en una posición en un vector. Al insertar el elemento, se debe producir un desplazamiento a la derecha de todos los elementos en las posiciones siguientes, el último elemento se pierde.

Por ejemplo:

v1 = [2, 4, 1, 7, 6, 2]

**insertar(v1, 5, 3)** #insertamos un 5 en la posición 3

=> v1 = [2, 4, 1, **5**, 7, 6]

In [ ]:
#Modificar la implementacion del ejercicio 4 pero modificando las posiciones del range

### **Ejercicio 6**

Escribir una función que elimine el elemento que ocupa una determinada posición de un vector. Al eliminar, los elementos a la derecha del eliminado, deben desplazarse a la izquierda un lugar y agregar un cero en la última posición.

Por ejemplo:

v1 = [4, 3, **5**, 8, 6, 7]

**eliminar(v1, 2)** #eliminamos el elemento de la posicion 2

=> v1 = [4, 3, **8, 6, 7, 0**]

In [ ]:
#v1 = [3, 5, 8, 6, 7, 7] 0 -> len(v1)-2 -> range(0,len(v1)-1)

def desplazarAIzquierda(vector:np.array)->np.array:
  for pos in range(0,len(v1)-1):
    vector[pos] = vector[pos+1]
  vector[len(vector)-1] = 0

v1  = np.array([4, 3, 5, 8, 6, 7])
print(v1)
desplazarAIzquierda(v1)
print(v1)

### **Ejercicio 7**

Escribir una función que elimine todas las apariciones de un determinado elemento de un vector. Al eliminar se deben insertar tantos ceros al final como elementos se eliminaron.

Por ejemplo:

arr1 = [4, 3, 5, 8, 6, 5, 7, 5]

**eliminarApariciones(arr1, 5)** #eliminamos todos los 5 del arreglo

=> arr1 = [4, 3, 8, 6, 7, **0, 0, 0**]

In [ ]:
#Recorrer array y usar funcion del ejercicio 5 para eliminar los elementos de a uno

### **Ejercicio 8**

Escribir un procedimiento que reciben un vector y:
- Imprime un subvector con los dos primeros elementos.
- Imprime un subvector con los tres últimos elementos.
- Imprime un subvector con los elementos desde la posiciones 2 hasta la 5
- Imprime un subvector con los elementos alternados cada dos. Por ej.: v1 = [2 , 1 , 4 , 5 , 2 , 7 , 9] debería imprimir [2 , 4 , 2 , 9]

Nota: Se debe utilizar la notacion **vector [ pos<sub>inicio</sub> : pos<sub>fin</sub> ]**

In [ ]:
arr1 = np.array([4, 3, 5, 8, 6, 5, 7, 5])
#print(arr1[2:6])

print(arr1[:2]) #primeros 2
print(arr1[len(arr1)-3:]) #ultimos 3
print(arr1[2:6])
print(arr1[::2])


### **Ejercicio 9**

Escribir una función **recursiva** que reciba un vector como parámetro y retorne la suma de todos sus elementos.

In [ ]:
#v1 = [2,3,1,5,4]
#suma(v1) = 2+3+1+5+4 = 2 + (3+1+5+4)
#suma(v) = v[0] + suma(v[1:])    si len(v) > 0
#           0                    si len(v) = 0

def sumaRecursiva(vector:np.array)->int:
  sumaTotal = None
  if len(vector) == 0:
    sumaTotal = 0
  else:
    sumaTotal = vector[0] + sumaRecursiva(vector[1:]) # 2 + sumaRecursiva([3,1,5,4])
  return sumaTotal

v1 = np.array([2,3,1,5,4])
print(sumaRecursiva(v1))

In [ ]:
#v1 = [2,3,1,5,4]
#suma(v1) = 2+3+1+5+4 = 2 + (3+1+5+4)
#suma(v) = v[0] + suma(v[1:])    si len(v) > 0
#           0                    si len(v) = 0

#sumar los elementos de v1 desde posicion 0 hasta el final -> sumaRecursiva2(v1, 0)
#sumar los elementos de v1 desde posicion 2 hasta el final -> sumaRecursiva2(v1, 2)
#.....
#sumar los elementos de v1 desde la ultima posicion hasta el final -> sumaRecursiva2(v1, len(v1))

def sumaRecursiva2(vector:np.array, posInicial:int=0)->int:
  sumaTotal = None
  if posInicial == len(vector)-1:
    sumaTotal = vector[posInicial]
  else:
    sumaTotal = vector[posInicial] + sumaRecursiva2(vector, posInicial+1)
  return sumaTotal

v1 = np.array([2,3,1,5,4])
print(sumaRecursiva2(v1))

### **Ejercicio 10**

Escribir una función que implemente de forma **recursiva** el algoritmo de **búsqueda binaria** sobre un vector.

https://es.khanacademy.org/computing/computer-science/algorithms/binary-search/a/binary-search

In [ ]:
#v tiene que estar ordenado
#busquedaBinaria(v,3) -> posicion del elemento 3 en v    si 3 esta en v
#                        None                            si 3 no esta en v
#v = [2,3,5,7,8,12,34,56]


  #busco posicion central
  #comparo datoBuscado con el elemento del vector en la posicion central
    # si el datoBuscado es igual -> lo encontre, es decir esta en la posicion central
    # si no es igual
      # si es menor -> busco el dato en la mitad inferior (0 - posicion central-1)
      # si es mayor -> busco el dato en la mitad superior (posicion central+1 - final)
import numpy as np
def busquedaBinaria(vector:np.array, datoBuscado:int, posInicial:int, posFinal:int)->int:
  posDato = None
  centro = (posInicial+posFinal)//2
  if posFinal < posInicial:
    posDato = None
  else:
    if vector[centro] == datoBuscado:
      posDato = centro
    elif datoBuscado < vector[centro]:
      posDato = busquedaBinaria(vector, datoBuscado, posInicial, centro-1)
    else:
      posDato = busquedaBinaria(vector, datoBuscado, centro+1, posFinal)
  return posDato

print(busquedaBinaria(np.array([3,7,12,15,24,37,42,54]),37,0,7))

### **Ejercicio 11**

Escribir una función **recursiva** que retorna *True* si una cadena de caracteres es un palíndromo y *False* en caso contrario.

Nota: Palíndromo es la forma elegante de "capicua"

In [ ]:
import numpy as np

def esPalindromo(cadena: str):
    salida = None
    if len(cadena) <= 1:
        salida = True
    elif cadena[0] != cadena[len(cadena)-1]:
        salida = False
    else:
        salida = esPalindromo(cadena[1:len(cadena)-1])
    return salida

p = np.array(['n','e','u','q','u','e','n'])
print(esPalindromo(p))

True


## **Matrices**

In [ ]:
import numpy as np

m1 = np.zeros((4,3), int)
print(m1)
m1[0,0] = 21
print(m1)
filas,cols = m1.shape
print(filas,cols)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[21  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]]
4 3


In [ ]:
m2 = np.array([[3,1,7],
               [6,2,9],
               [7,9,3],
               [1,9,5]])
for fila in m2:
  for elem in fila:
    print(elem)

3
1
7
6
2
9
7
9
3
1
9
5


In [ ]:
m2 = np.array([[3,1,7],
               [6,2,9],
               [7,9,3],
               [1,9,5]])
nFilas, nCols = m2.shape
for nFila in range(nFilas): #0,1,2,3
  for nCol in range(nCols): #0,1,2
    print("nfila=",nFila, "ncol=",nCol, m2[nFila,nCol])

nfila= 0 ncol= 0 3
nfila= 0 ncol= 1 1
nfila= 0 ncol= 2 7
nfila= 1 ncol= 0 6
nfila= 1 ncol= 1 2
nfila= 1 ncol= 2 9
nfila= 2 ncol= 0 7
nfila= 2 ncol= 1 9
nfila= 2 ncol= 2 3
nfila= 3 ncol= 0 1
nfila= 3 ncol= 1 9
nfila= 3 ncol= 2 5


In [ ]:
m2 = np.array([[3,1,7,3,1],
               [6,2,9,4,3],
               [7,9,3,9,8],
               [1,9,5,2,0]])
print(m2[1:3,1:4])

### **Ejercicio 12**

Escribir una función que recibe las dimensiones y retorna una matriz rellena de la siguiente forma: En la posición ( n , m ) debe contener n + m.

Por ejemplo:

mat1 = rellenaMatriz(4,3)

=> mat1 =

| <!--   --> |Col 0|Col 1|Col 2|
|------------|:---:|:---:|:---:|
| **Fila 0** |  0  |  1  |  2  |
| **Fila 1** |  1  |  2  |  3  |
| **Fila 2** |  2  |  3  |  4  |
| **Fila 3** |  3  |  4  |  5  |

In [ ]:
def rellenaMatriz(nFilas:int, nCols:int)->np.array:
  matrizSalida = np.zeros((nFilas,nCols), int)
  for nFila in range(nFilas):
    for nCol in range(nCols):
      matrizSalida[nFila, nCol] = nFila+nCol
  return matrizSalida

print(rellenaMatriz(40,30))

[[ 0  1  2 ... 27 28 29]
 [ 1  2  3 ... 28 29 30]
 [ 2  3  4 ... 29 30 31]
 ...
 [37 38 39 ... 64 65 66]
 [38 39 40 ... 65 66 67]
 [39 40 41 ... 66 67 68]]


### **Ejercicio 13**

Escribir una función que recibe una matriz cuadrada (N x N) y calcula la suma de los elementos que están por encima de la diagonal principal (excluyendo la diagonal).

En el ejemplo de la imagen, la función deberia retornar: *b + c + f*

![texto alternativo](https://economipedia.com/wp-content/uploads/Captura-de-Pantalla-2019-07-29-a-les-13.18.05-1.png)

In [ ]:
import numpy as np

def calcularElementosPorEncimaDeDiagonal(matrizCuadrada:np.array)-> np.array:

  nFilas,nCols=matrizCuadrada.shape
  salida=0

  for nFila in range(nFilas):
    for nCol in range(nCols):
      if  nCol>nFila:          # (0,0)no (0,1)si (1,0) no
        salida += matrizCuadrada[nFila][nCol]
  return salida


In [ ]:
v= np.array([[3,1,7],
            [6,2,9],
            [7,9,3]])
calcularElementosPorEncimaDeDiagonal(v)

17

### **Ejercicio 14**

Escribir una función que retorna *True* si una matriz cuadrada es matriz diagonal y *False* en caso contrario.

Una matriz cuadrada diagonal es una matriz que tiene ceros en todos sus elementos, menos en la diagonal principal (No importan los elementos de la diagonal principal, pueden ser cero o no).

**Si i, j son los índices de las filas y columnas de M**

**=> Una matriz M es diagonal si:**

**M [ i , j ] == 0 para todo i != j**

Matriz diagonal de 4 x 4:

| <!--   --> |Col 0|Col 1|Col 2|Col 3|
|------------|:---:|:---:|:---:|:---:|
| **Fila 0** |  0  |  0  |  0  |  0  |
| **Fila 1** |  0  |  2  |  0  |  0  |
| **Fila 2** |  0  |  0  |  4  |  0  |
| **Fila 3** |  0  |  0  |  0  |  0  |

In [ ]:
import numpy as np
def esDiagonal(matrizCuadrada:np.array)->bool:
  matrizD = True
  nFilas, nCols = matrizCuadrada.shape
  nFila = 0
  while matrizD==True and nFila < nFilas-1:
    nCol = nFila+1
    while matrizD==True and nCol < nCols:
      if matrizCuadrada[nFila,nCol]!=0 or matrizCuadrada[nCol,nFila]!=0:
        matrizD = False
      nCol += 1
    nFila += 1
  print(matrizD)

m = np.array([[1,0,0,0],
              [0,1,0,0],
              [2,0,1,0],
              [0,0,0,1]])
esDiagonal(m)

def esDiagonal2(matrizCuadrada:np.array)->bool:
  matrizD = True
  nFilas,nCols= matrizCuadrada.shape
  for nFila in range(nFilas):
    for nCol in range(nCols):
      if matrizCuadrada[nFila,nCol]!=0 or matrizCuadrada[nCol,nFila]!=0:
        matrizD = False
  return matrizD

m = np.array([[1,0,0,0],
              [0,1,0,0],
              [0,0,1,0],
              [1,0,0,1]])
esDiagonal(m)


False
False


### **Ejercicio 15**

Escribir una función que retorna *True* si una matriz cuadrada de enteros es simétrica y *False* en caso contrario.

Una matriz simétrica es como la de la imagen (no importan los elementos de la diagonal principal):

![texto alternativo](https://economipedia.com/wp-content/uploads/Captura-de-Pantalla-2019-09-23-a-les-15.58.25.png)

Es decir:

**Si i, j son los índices de las filas y columnas de M**

**=> Una matriz M es simétrica si:**

**M [ i , j ] == M[ j, i ] para todo i != j**

Matriz simétrica de 4 x 4:

| <!--   --> |Col 0|Col 1|Col 2|Col 3|
|------------|:---:|:---:|:---:|:---:|
| **Fila 0** |  2  |  1  |  0  |  5  |
| **Fila 1** |  1  |  2  |  9  |  7  |
| **Fila 2** |  0  |  9  |  0  |  8  |
| **Fila 3** |  5  |  7  |  8  |  4  |

In [ ]:
def esSimetrica(matriz:np.array)->bool:
  matrizEsSimetrica = True
  nFilas, nCols = matriz.shape
  for nFila in range(nFilas):
    for nCol in range(nCols):
      if matriz[nFila,nCol] != matriz[nCol,nFila]:
        matrizEsSimetrica = False
  return matrizEsSimetrica

m=np.array([[2,1,0,5],
            [1,2,9,7],
            [0,9,0,8],
            [5,7,8,4]])
print(esSimetrica(m))

#m[1,2] = m[1][2]