<a href="https://colab.research.google.com/github/LSantana32/estructuraDeDatos-UNAHUR/blob/main/Copia_de_Trabajo_practico_6_Diccionario_com1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png) **Trabajo Práctico 6: Diccionarios** ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png)

En este trabajo práctico, vamos a trabajar con la estructura de datos **Diccionario** basado en el conjunto de Python. Recuerden crear una copia de este archivo en su ***Google Drive*** para tener permisos de edición.

### Sergio: **sergio.gonzalez@unahur.edu.ar** ###

In [ ]:
conj1 = set()
print(conj1)
conj1.add(1);conj1.add(10);conj1.add(2);conj1.add(4);
print(conj1)

set()
{1, 10, 2, 4}


In [ ]:
tupla1 = (2,[1,2,3,3])
tupla1[1].append(4)
print(tupla1)

(2, [1, 2, 3, 3, 4])


### **Ejercicio 1**

Implementar el TDA **Diccionario (Map)**, con las siguientes operaciones (Solo lo tienen que usar, ya esta implementado por nosotros, pero repasen el funcionamiento):
- Crear (**\_\_init__()**).
- **\_\_repr__()**: Para poder imprimir por consola.
- **insertar(clave, significado)**: Inserta el par **<clave , significado>**, si la clave ya existe no debe modificar el diccionario.
- **Asignación con "dicc[clave] = significado"**: Permite modificar significados de claves existentes y agregar nuevos pares. Esto se realiza implementado la función **\_\_setitem__()**.
- **get(clave)**: Recibe una clave y retorna su significado, si la clave no existe lanza una excepción.
- **Obtener con "dicc[clave]"**: Similar a **get**, pero con el operador **"[ ]"**. Esto se realiza implementando la función **\_\_getitem__()**.
- **len()**: Retorna la cantidad de pares **<clave , significado>** en el diccionario.
- **getKeys()**: Retorna lista con claves.
- **getValues()**: Retorna lista con significados.
- **Operador "in"**: Permite la búsqueda dentro del diccionario por las claves, es decir podemos hacer **"if clave in diccionario"**.
- **remove(clave)**: Elimina el par clave-significado que contiene la clave que recibe como parámetro
- **clone()**: Genera nuevo diccionario con el mismo contenido
- **clear()**: Vacia diccionario

Si quieren iterar el diccionario deben hacer (por ejemplo para imprimir todos los pares clave-significado en diferentes lineas):

    
    for clave in diccionario.keys():
        print(clave, diccionario.get(clave))

O el equivalente con el operador **"[ ]"**:


    for clave in diccionario.keys():
        print(clave, dicionario[clave])

Aunque tengamos el operador **"in"** este sirve solo para búsquedas y no para iterar en diccionario, entonces no se puede hacer:


    for clave in diccionario:








In [12]:
import copy as cp

class Diccionario:
  #######TDA tupla clave-significado#########################
  class __TuplaDic:
    def __init__(self, key, value):
      self.__data = (key,value)

    def __repr__(self):
      return str(self.__data)

    def __eq__(self, key):
      return self.__data[0] == key

    def __hash__(self):
      return hash(self.__data[0])

    def getKey(self):
      return self.__data[0]

    def getValue(self):
      return self.__data[1]
  ############################################################

  ###Constructor recibe dos listas de claves y significados en orden
  def __init__(self, keys = None, values = None):
    self.__diccionario = set()
    if keys != None:
      if len(keys) == len(values):
        for i in range(len(keys)):
          self[keys[i]] = values[i]
      else:
        raise Exception("Las listas de pares clave-significado deben tener la misma cantidad")

  def __repr__(self):
    return str(self.__diccionario)

  ###Asignacion usando [], se recibe clave entre corchetes / Permite reemplazar aunque exista la clave
  def __setitem__(self, key = None, value = None):
    if key != None:
      if key in self:
        self.__diccionario.remove(key)
      self.__diccionario.add(Diccionario.__TuplaDic(key,value))

  ###No inserta si existe la clave, es decir, si la clave existe en el dicc no modifica el valor
  def insert(self, key = None, value = None):
    if key != None:
      self.__diccionario.add(Diccionario.__TuplaDic(key,value))

  ###Elimina si existe la clave, es decir, si la clave existe en el dicc elimina el par clave-valor
  ###Sino existe la clave, no hace nada
  def remove(self, key):
    if key in self:
        valor = self[key]
        self.__diccionario.remove(key)
        return valor

  ###Vacia dicc
  def clear(self):
    self.__diccionario = set()

  ###Clonar dicc
  def clone(self):
    return cp.deepcopy(self)

  ###Acceso a valores usando [], se recibe clave entre corchetes
  def __getitem__(self, key):
    value = None
    flag = False
    for tuplaDic in self.__diccionario:
      if tuplaDic.getKey() == key:
        value = tuplaDic.getValue()
        flag = True
    if flag:
      return value
    else:
      raise Exception("No existe la clave %s en el diccionario" % (key))

  ###Retorna valor de la clave que se recibe por parametro
  def get(self, key):
    value = None
    flag = False
    for tuplaDic in self.__diccionario:
      if tuplaDic.getKey() == key:
        value = tuplaDic.getValue()
        flag = True
    if flag:
      return value
    else:
      raise Exception("No existe la clave %s en el diccionario" % (key))

  ###Retorna lista con claves
  def keys(self):
    return [x.getKey() for x in self.__diccionario]

  ###Retorna lista con valores
  def values(self):
    return [x.getValue() for x in self.__diccionario]

  ###Operador "in"
  def __contains__(self, key):
    return key in self.__diccionario

  ###Tamaño de diccionario
  def len(self):
    return len(self.__diccionario)

In [ ]:
dic1 = Diccionario()
dic1.insert(1,"uno")
dic1.insert(2,[2,3,4,5])
print(dic1)
var = 1
print(dic1[var])
dic1[2] = "hola"
print(dic1)
dic1.remove(1)
print(dic1)

{(1, 'uno'), (2, [2, 3, 4, 5])}
uno
{(1, 'uno'), (2, 'hola')}
{(2, 'hola')}


In [ ]:
dic2 = Diccionario((1,2,3,4),("casa", "perro", "gato", "auto"))
for clave in dic2.keys():
  print(clave, dic2[clave])

print(40 in dic2)


1 casa
2 perro
3 gato
4 auto
False


In [ ]:
notas = Diccionario(("juan","pedro","maria"),([],[],[]))
print(notas)
notas["juan"].append(4)
print(notas)
print(dic2.len())

{('juan', []), ('pedro', []), ('maria', [])}
{('juan', [4]), ('pedro', []), ('maria', [])}
4


### A partir del **Ejercicio 2** vamos a trabajar **fuera del TDA Diccionario** usando la interface que creamos en el **Ejercicio 1**. Es decir,se pueden usar solo las operaciones de la interface, no se puede acceder a los componentes internos del TDA. Si necesitan estructuras auxiliares, pueden usar cualquiera de las estructuras que vimos hasta ahora: Arreglos, Listas, Pilas, Colas, Diccionarios.

### **Ejercicio 2**

Escribir un programa que declare un Diccionario de **<entero , entero>** (clave entero y significado entero) y le agrege 4 pares. Luego debe mostrar el diccionario por pantalla y su tamaño.

Finalmente, redefinir 2 significados y volver a imprimir.

In [ ]:
dicc1= Diccionario()
dicc1.insert(1,1)
dicc1.insert(13,4)  #(clave,valor)
dicc1[23]=123     #[clave]=valor
dicc1[212]=939
print (dicc1)

dicc1[23]=77
dicc1[212]=66      #redefinir diccionario
print(dicc1)


{(1, 1), (212, 939), (13, 4), (23, 123)}
{(1, 1), (212, 66), (13, 4), (23, 77)}


### **Ejercicio 3**

Escribir un diccionario con sinónimos. Luego intentar insertar dos pares **<clave , significado>** con claves **repetidas** con la operacion **insert** y ver que sucede.

In [ ]:
dicc3=Diccionario()
dicc3[1]=" uno"
dicc3[2]="dos"
print(dicc3)
dicc3.insert(1,1)             # no se modifica el value a pesar de que haga insert
dicc3.insert(2,2)
print(dicc3)
print(dicc3[1])

{(1, ' uno'), (2, 'dos')}
{(1, ' uno'), (2, 'dos')}
 uno


### **Ejercicio 4**

Escribir una función que dado una lista de enteros me devuelve otra(no necesariamente en el mismo orden) sin los numeros repetidos.

Por ejemplo:

Lista de entrada = [1 , 3 , 4 , 1 , 2 , 4 , 3 , 2]

Lista de salida = [1 , 3 , 2, 4]

In [ ]:
def listaSinRepetidos2(lista):
  dic = Diccionario()
  for element in lista:
    dic.insert(element,None)
  return dic.keys()        #asi podemos retornar keys y values


# set es el tda Conjunto
# ese tda tiene un constructor que recive una lista como parametro
def listaSinRepetidos(lista):
   conj=set(lista)              #asi pasas de lista a conjunto, anulando los repetidos
   return list(conj)            #despues lo pasas a lista y te queda la lista sin repetidos

list4=[1,3,4,1,2,4,3,2]
print(listaSinRepetidos2(list4))



[1, 2, 3, 4]


### **Ejercicio 5**

Rehacer le ejercicio 4 pero retornando un diccionario en lugar de una lista.

Por ejemplo:

Lista de entrada = [1 , 3 , 4 , 1 , 2 , 4 , 3 , 2]

Diccionario de salida = { (1 , None) , (3 , None) , (4 , None) , (2 , None) }

In [ ]:
def listaSinRepetidos5(lista):
  dic = Diccionario()
  for element in lista:
    dic.insert(element,None)
  return dic

list5=[1,3,4,1,2,4,3,2]
print(listaSinRepetidos5(list5))


{(1, None), (2, None), (3, None), (4, None)}


### **Ejercicio 6**

Escribir una función que recibe una lista de números como parámetro y devuelve un diccionario con los números de la lista como claves y la cantidad de apariciones de cada uno como su significado.

Por ejemplo:

Lista de entrada = [1 , 3 , 4 , 2 , 1 , 3 , 1 , 4 , 2 , 5 , 2]

Diccionario de salida = { (1 , 3) , (3 , 2) , (4 , 2) , (2 , 3) , (5 , 1) }

In [ ]:
def listaADiccRepetido(lista):
  salida=Diccionario()
  for elem in lista:
    if not elem in salida:
      salida[elem]=1
    else:
      salida[elem]+=1
  return salida

list=[1,3,4,2,1,3,1,4,2,5,2]
listaADiccRepetido(list)

{(1, 3), (2, 3), (3, 2), (4, 2), (5, 1)}

### **Ejercicio 7**

Escribir una función que recibe dos diccionarios y devuelve otro con la mezcla de los dos, para las claves repetidas, se queda con los significados de primer diccionario.

Por ejemplo:

Diccionario de entrada 1 = { (1 , 3) , (3 , 2) , (4 , 4) , (2 , 3) , (5 , 1) }

Diccionario de entrada 2 = { (10 , 3) , (3 , 5) , (2 , 30) , (8 , 1) , (9 , 3) }

Diccionario de salida = { (1 , 3) , (3 , 2) , (4 , 4) , (2 , 3) , (5 , 1) , (10 , 3) , (8 , 1) , (9 , 3) }

In [ ]:
d1= Diccionario()
d1.insert(1,3)
d1.insert(3,2)
d1.insert(4,4)
d1.insert(2,3)
d1.insert(5,1)

d2= Diccionario()
d2.insert(10,3) #         <------------------------------------------------
d2.insert(3,5)#                                                            |
d2.insert(2,30)#                                                           |
d2.insert(8,1)#                                                            |
d2.insert(9,3)#                                                            |
#                                                                          |
def mezDic(a,b):#                                                          |
  salida=a.clone()#                                                        |
  for clave in b.keys():#                                                  |
    salida.insert(clave,b[clave]) #b[clave]=SIGNIFICADO       ==        d2[10]=3
  return salida

mezDic(d1,d2)





{(1, 3), (2, 3), (3, 2), (4, 4), (5, 1), (8, 1), (9, 3), (10, 3)}

### **Ejercicio 8**

Escribir una función que modele el problema de administrar las materias que cursa un alumno.
Es decir que reciba un diccionario, un alumno y una materia y agregue esa materia a las materias que cursa.

**Nota: La lista de materias de cada alumno no debe tener materias repetidas.**

Por ejemplo:

Diccionario = { ( "Alumno1" , ["Materia1" , "Materia2"] )   ,   ( "Alumno2", [ "Materia2" , "Materia3" , "Materia4" ] ) }


In [ ]:
dic = Diccionario()

def administrarMaterias(diccionario,alumn,mat):
  if not diccionario.__contains__(alumn):
    diccionario.insert(alumn,[mat])
  else:
    if not mat in diccionario[alumn]:
      diccionario[alumn].append(mat)

administrarMaterias(dic, "Alumno1", "Materia1")
administrarMaterias(dic, "Alumno1", "Materia2")
administrarMaterias(dic, "Alumno1", "Materia2")
administrarMaterias(dic, "Alumno2", "Materia2")
administrarMaterias(dic, "Alumno2", "Materia3")
print(dic)



{('Alumno1', ['Materia1', 'Materia2']), ('Alumno2', ['Materia2', 'Materia3'])}


### **Ejercicio 9**

Tenemos un diccionario del tipo **<Entero , Lista de enteros>** (clave número entero, significado lista de enteros) que dado un numero **X**, guarda las posibles combinaciones de ese número con otros.

Escribir una función que recibe un diccionario de este tipo y devuelve una lista con los posibles pares de números (en formato de tupla).

Por ejemplo:

Diccionario de entrada = { (5 , [5 , 3 , 7 ] )  ,  ( 8, [ 15 , 3 ] ) }

Lista de salida = [ (5 , 5) ,(5 , 3) , (5 , 7) , (8 , 15) , (8 , 3) ]



In [ ]:
def paresNumeros(diccionario):
  listaAux=[]
  for key in diccionario.keys():
    for value in diccionario[key]:
      listaAux.append((key,value))
  return listaAux


dicc=Diccionario()
dicc.insert(5,[5,3,7])
dicc.insert(8,[15,3])
#print(dicc)
paresNumeros(dicc)

[(8, 15), (8, 3), (5, 5), (5, 3), (5, 7)]

### **Ejercicio 10**

Escribir una función que haga lo inverso del Ejercicio 9.

Por ejemplo:

Lista de entrada = [ (5 , 5) ,(5 , 3) , (5 , 7) , (8 , 15) , (8 , 3) ]

Diccionario de salida = { (5 , [5 , 3 , 7 ] )  ,  ( 8, [ 15 , 3 ] ) }




In [7]:
def inversa9(lista):
  dicc=Diccionario()

  for tupla in lista:
    dicc.insert(tupla[0],[])
    dicc[tupla[0]].append(tupla[1])
  return dicc



list5=[(5,5),(5,3),(5,7),(8,15),(8,3)]
#print(list5)
inversa9(list5)

{(8, [15, 3]), (5, [5, 3, 7])}

### **Ejercicio 11**

Escribir el TDA **MatrizDePixels**, que modele una matriz de pixels (imagen) de **N x M** usando el tipo array del paquete numpy, donde cada pixel tiene un color representado por un número entero entre **0 y 255**.

Hacer las operaciones del TDA para crear una MatrizDePixels (por defecto llena de ceros), leer y escribir pixels.

Luego pruebenla con estos ejemplos:

**a)** Crear una MatrizDePixels de **100 x 100** y agregarle valores a dos pixels.

**b)** Crear una MatrizDePixels de **100000 x 50000** y agregarle valores a dos pixels.

Explicar porque el inciso **b** da un error




In [11]:
import numpy as np

class MatrizDePixels:
  def __init__(self,cantFilas:int,cantCols:int):
    self.__pixel=np.zeros((cantFilas,cantCols),int)

  def __repr__(self):
    return str(self.__pixel)

  def escribirPixel(self,cantFilas,cantCols,valor)->None:
    self.__pixel[cantFilas,cantCols]=valor

  def leerPixel(self,cantFilas,cantCols):
    return self.__pixel[cantFilas,cantCols]


imagen1 = MatrizDePixels(1000,1000)
imagen1.escribirPixel(98,98,156)
imagen1.escribirPixel(1,1,50)
print(imagen1)



[[ 0  0  0 ...  0  0  0]
 [ 0 50  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


Ahora escribir el TDA **MatrizDePixelsDict**, que modele una matriz de pixels (imagen) de **N x M** usando un diccionario de **<(fila,columna) , pixel>**, donde cada pixel tiene un color representado por un número entero entre **0 y 255** y el par **(fila,columna)** indica la posición del pixel en la matriz.

Hacer las operaciones del TDA para crear una MatrizDePixelsDict (por defecto llena de ceros), leer y escribir pixels.

Luego pruebenla con estos ejemplos:

**a)** Crear una MatrizDePixelsDict de **100 x 100** y agregarle valores a dos pixels.

**b)** Crear una MatrizDePixelsDict de **100000 x 50000** y agregarle valores a dos pixels.

Explicar porque el inciso **b** ahora si funciona

**Nota:** Si importan el paquete **sys** pueden usar la función **sys.getsizeof(variable)** que retorna el espacio que ocupa una variable en memoria.

In [51]:
class MatrizDePixels2:
  def __init__(self,cantFilas:int,cantCols:int):
    self.__x=cantFilas
    self.__y=cantCols
    self.__pixel=Diccionario()

  def __repr__(self):
    return f"{self.__pixel} ({self.__x}, {self.__y})"

  def escribirPixel(self,cantFilas,cantCols,valor)->None:
    self.__pixel[(cantFilas,cantCols)]=valor

  def leerPixel(self,cantFilas,cantCols):
    valor=0
    if (cantFilas,cantCols) in self.__pixel:
      valor = self.__imagen[(cantFilas,cantCols)]
    return valor

imagen1 = MatrizDePixels2(1000,1000)
#imagen1.escribirPixel(98,98,156)
#imagen1.leerPixel(97,98)
#print(imagen1)


### **Ejercicio 12**

Implementar la suma matrices como operación en el TDA **MatrizDePixelsDict** implementado en el Ejercicio 11.

In [47]:
import numpy as np
def sumaMatrices(matriz1,matriz2):
  nFilas,nCols=matriz1.shape
  matrizSalida=np.zeros((nFilas,nCols))
  for nFila in range(nFilas):
    for nCol in range(nCols):
      matrizSalida[nFila,nCol]=matriz1[nFila,nCol]+matriz2[nFila,nCol]
  return matrizSalida



In [48]:
n = np.array([[1,0,0,0],
              [0,1,0,0],
              [10,0,1,0],
              [0,0,0,1]])

m = np.array([[1,0,0,20],
              [0,2,0,0],
              [10,0,1,0],
              [0,0,0,1]])
sumaMatrices(n,m)


array([[ 2.,  0.,  0., 20.],
       [ 0.,  3.,  0.,  0.],
       [20.,  0.,  2.,  0.],
       [ 0.,  0.,  0.,  2.]])

In [64]:
def sumaDeDicc(dicc1,dicc2):
  matrSalida=Diccionario()
  for clave in dicc1:
      matrSalida[clave].insert(clave)
  return matrSalida


In [65]:
#falta hacer la suma de diccionarios